name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.10', '1.11']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: ${{ matrix.julia-version }}
    
    - name: Cache Julia packages
      uses: julia-actions/cache@v2
    
    - name: Install dependencies
      run: |
        julia --project=. -e '
          using Pkg
          
          # Add the CliMA registry first
          Pkg.Registry.add(RegistrySpec(url="https://github.com/CliMA/ClimaRegistry"))
          
          # Update registries
          Pkg.Registry.update()
          
          # Add standard library dependencies
          Pkg.add(["Statistics", "Printf", "Dates"])
          
          # Add ClimaOcean directly from GitHub repository
          Pkg.add(PackageSpec(url="https://github.com/CliMA/ClimaOcean.jl"))
          
          # Now instantiate the rest of the dependencies
          Pkg.instantiate()
          
          # Show status for debugging
          @info "Package status:"
          Pkg.status()'
    
    - name: Run tests
      run: |
        julia --project=. -e 'using Pkg; Pkg.test()'