name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.10', '1.11']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: ${{ matrix.julia-version }}
    
    - name: Cache Julia packages
      uses: julia-actions/cache@v2
    
    - name: Install dependencies
      run: |
        julia --project=. -e 'using Pkg; Pkg.add("Statistics"); Pkg.add("Printf"); Pkg.add("Dates"); Pkg.instantiate()'
    
    - name: Run tests
      run: |
        julia --project=. -e 'using Pkg; Pkg.test()'
