name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.10', '1.11']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: ${{ matrix.julia-version }}
    
    - name: Cache Julia packages
      uses: julia-actions/cache@v2
    
    - name: (Temporary) Add specific ClimaOcean branch (ss/omip-prototype)
      run: |
        julia --project=. -e '
          using Pkg
          Pkg.add(url="https://github.com/CliMA/ClimaOcean.jl.git", rev="ss/omip-prototype")
        '

    - name: Run tests
      run: |
        julia --project=. -e '
          using Pkg
          Pkg.add("Test")
          Pkg.test()'