# .github/workflows/CompatHelper.yml
name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *  # Daily at midnight
  workflow_dispatch:

# Add explicit permissions for the GITHUB_TOKEN
permissions:
  contents: write
  pull-requests: write

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Check for compat updates
        uses: julia-actions/CompatHelper@v1
        with:
          pr_title_prefix: "CompatHelper:"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}